# Generated by Django 5.0.1 on 2024-02-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitmap_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitmapConfig',
            new_name='Bitmap60Config',
        ),
    ]
